name: Run Unit Tests

on: [push]

jobs:
  run-unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@8912a9102ac27614460f54aedde9e1e7f9aec20d
        with:
          version: 11
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "pnpm"
      - run: pnpm ci
      - name: generate prisma client
        run: pnpx prisma generate
      - run: pnpm test
